import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { Concept } from "@solana-ontology/core";
import { generateRustStruct, toSnakeCase } from "./type-gen.js";
import { generateRustPdaHelper } from "./pda-gen.js";

export interface RustGenerateOptions {
  outputDir: string;
}

export interface GeneratedRustFile {
  path: string;
  content: string;
}

/**
 * Generate a single Rust file for a concept.
 */
export function generateConceptRustFile(concept: Concept): GeneratedRustFile {
  const snakeName = toSnakeCase(concept.canonicalName);
  const parts: string[] = [];

  parts.push("// AUTO-GENERATED by @solana-ontology/generator-rust");
  parts.push("// Do not edit manually.");
  parts.push("");
  parts.push("use solana_sdk::pubkey::Pubkey;");
  parts.push("");

  parts.push(generateRustStruct(concept));

  const pdaHelper = generateRustPdaHelper(concept);
  if (pdaHelper) {
    parts.push("");
    parts.push(pdaHelper);
  }

  return {
    path: `${snakeName}.rs`,
    content: parts.join("\n"),
  };
}

/**
 * Generate a mod.rs barrel file for Rust.
 */
export function generateRustModFile(concepts: Concept[]): string {
  const lines: string[] = ["// AUTO-GENERATED by @solana-ontology/generator-rust", ""];

  for (const concept of concepts) {
    const snakeName = toSnakeCase(concept.canonicalName);
    lines.push(`pub mod ${snakeName};`);
  }

  return lines.join("\n");
}

/**
 * Generate all Rust files for an array of concepts and write them to disk.
 */
export function generateAllRust(
  concepts: Concept[],
  options: RustGenerateOptions,
): GeneratedRustFile[] {
  const allFiles: GeneratedRustFile[] = [];
  mkdirSync(options.outputDir, { recursive: true });

  for (const concept of concepts) {
    const file = generateConceptRustFile(concept);
    const fullPath = join(options.outputDir, file.path);
    writeFileSync(fullPath, file.content, "utf-8");
    allFiles.push({ path: fullPath, content: file.content });
  }

  const modContent = generateRustModFile(concepts);
  const modPath = join(options.outputDir, "mod.rs");
  writeFileSync(modPath, modContent, "utf-8");
  allFiles.push({ path: modPath, content: modContent });

  return allFiles;
}
