/**
 * Generate typed client library from ontology concepts.
 * Produces ObjectTypes.ts, ActionTypes.ts, Client.ts, Queries.ts.
 */

import type { Concept, ConceptProperty } from "@solana-ontology/core";
import type { ClientGenConfig, GeneratedClientFile } from "./types.js";

/**
 * Map ontology type to TypeScript type.
 */
function mapToTsType(type: string): string {
  const typeMap: Record<string, string> = {
    u8: "number",
    u16: "number",
    u32: "number",
    u64: "bigint",
    u128: "bigint",
    i8: "number",
    i16: "number",
    i32: "number",
    i64: "bigint",
    i128: "bigint",
    f32: "number",
    f64: "number",
    bool: "boolean",
    Address: "string",
    PublicKey: "string",
    string: "string",
    bytes: "Uint8Array",
  };
  if (type.startsWith("Option<")) {
    const inner = type.slice(7, -1);
    return `${mapToTsType(inner)} | null`;
  }
  if (type.startsWith("Vec<")) {
    const inner = type.slice(4, -1);
    return `${mapToTsType(inner)}[]`;
  }
  return typeMap[type] ?? "unknown";
}

/**
 * Generate ObjectTypes.ts — typed interfaces for each concept.
 */
export function generateObjectTypes(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n";
  code += "// DO NOT EDIT — regenerate with: solana-ontology generate client\n\n";

  for (const concept of concepts) {
    code += `/** ${concept.purpose} */\n`;
    code += `export interface ${concept.canonicalName} {\n`;
    code += `  pubkey: string;\n`;

    for (const prop of concept.properties ?? []) {
      const tsType = mapToTsType(prop.type);
      const optional = !prop.required ? "?" : "";
      code += `  ${prop.name}${optional}: ${tsType};\n`;
    }

    code += `}\n\n`;
  }

  return code;
}

/**
 * Generate ActionTypes.ts — typed action submission functions.
 */
export function generateActionTypes(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n\n";
  code += "import type { ActionInstruction } from '@solana-ontology/sdk';\n\n";

  for (const concept of concepts) {
    if (!concept.stateMachine?.transitions) continue;

    for (const transition of concept.stateMachine.transitions) {
      const funcName = `${concept.canonicalName}_${transition.via}`;
      const params = (concept.properties ?? [])
        .filter((p) => p.required && p.name !== "pubkey")
        .map((p) => `${p.name}: ${mapToTsType(p.type)}`)
        .join(", ");

      code += `/** ${transition.via}: ${transition.from} → ${transition.to} for ${concept.canonicalName} */\n`;
      code += `export async function ${funcName}(${params}): Promise<ActionInstruction> {\n`;
      code += `  // TODO: Implement using ActionBuilder + instruction compiler\n`;
      code += `  throw new Error('Not implemented — use OntologyClient.dispatchAction()');\n`;
      code += `}\n\n`;
    }
  }

  return code;
}

/**
 * Generate Client.ts — main client class.
 */
export function generateClient(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n\n";
  code += "import type { OntologyClient } from '@solana-ontology/sdk';\n";
  code += "import type * as ObjectTypes from './ObjectTypes.js';\n\n";

  code += "export class SolanaOntologyClient {\n";
  code += "  constructor(private client: OntologyClient) {}\n\n";

  for (const concept of concepts) {
    code += `  /** Fetch a ${concept.canonicalName} by pubkey */\n`;
    code += `  async ${concept.canonicalName}(pubkey: string): Promise<ObjectTypes.${concept.canonicalName} | null> {\n`;
    code += `    const account = await this.client.fetchAccount(pubkey);\n`;
    code += `    return account as ObjectTypes.${concept.canonicalName} | null;\n`;
    code += `  }\n\n`;
  }

  code += "}\n";
  return code;
}

/**
 * Generate Queries.ts — async iterator + filter functions.
 */
export function generateQueries(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n\n";
  code += "import type { OntologyClient } from '@solana-ontology/sdk';\n";
  code += "import type * as ObjectTypes from './ObjectTypes.js';\n\n";

  for (const concept of concepts) {
    const name = concept.canonicalName;
    code += `export async function* iterate${name}(client: OntologyClient, programId: string): AsyncGenerator<ObjectTypes.${name}> {\n`;
    code += `  // TODO: Implement using getProgramAccounts with pagination\n`;
    code += `  yield* [];\n`;
    code += `}\n\n`;

    code += `export async function filter${name}(\n`;
    code += `  client: OntologyClient,\n`;
    code += `  programId: string,\n`;
    code += `  predicate: (account: ObjectTypes.${name}) => boolean,\n`;
    code += `): Promise<ObjectTypes.${name}[]> {\n`;
    code += `  const results: ObjectTypes.${name}[] = [];\n`;
    code += `  for await (const account of iterate${name}(client, programId)) {\n`;
    code += `    if (predicate(account)) results.push(account);\n`;
    code += `  }\n`;
    code += `  return results;\n`;
    code += `}\n\n`;
  }

  return code;
}

/**
 * Generate all client files.
 */
export function generateClientFiles(
  concepts: Concept[],
  config: ClientGenConfig,
): GeneratedClientFile[] {
  const files: GeneratedClientFile[] = [
    { path: "ObjectTypes.ts", content: generateObjectTypes(concepts) },
    { path: "ActionTypes.ts", content: generateActionTypes(concepts) },
    { path: "Client.ts", content: generateClient(concepts) },
  ];

  if (config.generateQueries) {
    files.push({ path: "Queries.ts", content: generateQueries(concepts) });
  }

  if (config.generateReact) {
    files.push({ path: "Hooks.ts", content: generateReactHooks(concepts) });
  }

  // Index barrel
  files.push({
    path: "index.ts",
    content: [
      "export * from './ObjectTypes.js';",
      "export * from './ActionTypes.js';",
      "export * from './Client.js';",
      config.generateQueries ? "export * from './Queries.js';" : "",
      config.generateReact ? "export * from './Hooks.js';" : "",
    ]
      .filter(Boolean)
      .join("\n"),
  });

  return files;
}

/**
 * Generate React hooks for each concept.
 */
function generateReactHooks(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n\n";
  code += "import { useEffect, useState } from 'react';\n";
  code += "import type { OntologyClient } from '@solana-ontology/sdk';\n";
  code += "import type * as ObjectTypes from './ObjectTypes.js';\n\n";

  for (const concept of concepts) {
    const name = concept.canonicalName;
    code += `export function use${name}(client: OntologyClient | null, pubkey: string | null) {\n`;
    code += `  const [data, setData] = useState<ObjectTypes.${name} | null>(null);\n`;
    code += `  const [loading, setLoading] = useState(false);\n`;
    code += `  const [error, setError] = useState<Error | null>(null);\n\n`;
    code += `  useEffect(() => {\n`;
    code += `    if (!client || !pubkey) return;\n`;
    code += `    setLoading(true);\n`;
    code += `    client.fetchAccount(pubkey)\n`;
    code += `      .then((acc) => setData(acc as ObjectTypes.${name} | null))\n`;
    code += `      .catch(setError)\n`;
    code += `      .finally(() => setLoading(false));\n`;
    code += `  }, [client, pubkey]);\n\n`;
    code += `  return { data, loading, error };\n`;
    code += `}\n\n`;
  }

  return code;
}
