/**
 * Generate typed client library from ontology concepts.
 * Produces ObjectTypes.ts, ActionTypes.ts, Client.ts, Queries.ts.
 */

import type { Concept, ConceptProperty } from "@solana-ontology/core";
import type { ClientGenConfig, GeneratedClientFile } from "./types.js";

/**
 * Map ontology type to TypeScript type.
 */
function mapToTsType(type: string): string {
  const typeMap: Record<string, string> = {
    u8: "number",
    u16: "number",
    u32: "number",
    u64: "bigint",
    u128: "bigint",
    i8: "number",
    i16: "number",
    i32: "number",
    i64: "bigint",
    i128: "bigint",
    f32: "number",
    f64: "number",
    bool: "boolean",
    Address: "string",
    PublicKey: "string",
    string: "string",
    bytes: "Uint8Array",
  };
  if (type.startsWith("Option<")) {
    const inner = type.slice(7, -1);
    return `${mapToTsType(inner)} | null`;
  }
  if (type.startsWith("Vec<")) {
    const inner = type.slice(4, -1);
    return `${mapToTsType(inner)}[]`;
  }
  return typeMap[type] ?? "unknown";
}

/**
 * Generate ObjectTypes.ts — typed interfaces for each concept.
 */
export function generateObjectTypes(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n";
  code += "// DO NOT EDIT — regenerate with: solana-ontology generate client\n\n";

  for (const concept of concepts) {
    code += `/** ${concept.purpose} */\n`;
    code += `export interface ${concept.canonicalName} {\n`;
    code += `  pubkey: string;\n`;

    for (const prop of concept.properties ?? []) {
      const tsType = mapToTsType(prop.type);
      const optional = !prop.required ? "?" : "";
      code += `  ${prop.name}${optional}: ${tsType};\n`;
    }

    code += `}\n\n`;
  }

  return code;
}

/** Map a textual IDL arg type to the TS type accepted by the SDK borsh encoder. */
function mapIdlArgTypeToTs(type: string): string {
  const option = type.match(/^option<(.+)>$/);
  if (option) return `${mapIdlArgTypeToTs(option[1])} | null`;
  const vec = type.match(/^vec<(.+)>$/);
  if (vec) return `${mapIdlArgTypeToTs(vec[1])}[]`;
  const array = type.match(/^array<(.+),\s*\d+>$/);
  if (array) return array[1] === "u8" ? "Uint8Array" : `${mapIdlArgTypeToTs(array[1])}[]`;
  const scalar: Record<string, string> = {
    bool: "boolean",
    u8: "number",
    u16: "number",
    u32: "number",
    i8: "number",
    i16: "number",
    i32: "number",
    f32: "number",
    f64: "number",
    u64: "bigint",
    u128: "bigint",
    i64: "bigint",
    i128: "bigint",
    string: "string",
    pubkey: "string",
    bytes: "Uint8Array",
  };
  return scalar[type] ?? "unknown";
}

/** True when a concept's idlInstruction carries enough data to build instructions. */
function hasInstructionData(concept: Concept): boolean {
  const ref = concept.idlInstruction;
  return !!(
    ref?.instructionName &&
    ref.discriminator &&
    ref.args &&
    ref.accounts &&
    ref.accounts.length > 0 &&
    (ref.programId ?? concept.programId)
  );
}

/**
 * Generate ActionTypes.ts — typed action submission functions.
 *
 * Transitions whose instruction is described by the concept's idlInstruction
 * (programId, discriminator, args, accounts) get a real builder wired to the
 * SDK's compileInstruction. Transitions without that data throw an explicit
 * "no IDL data" error — unsupported, not unimplemented.
 */
export function generateActionTypes(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n";
  code += "// DO NOT EDIT — regenerate with: solana-ontology generate client\n\n";
  code += "import { compileInstruction, type ActionInstruction } from '@solana-ontology/sdk';\n\n";

  for (const concept of concepts) {
    if (!concept.stateMachine?.transitions) continue;

    const ref = concept.idlInstruction;
    const buildable = hasInstructionData(concept);
    const programId = ref?.programId ?? concept.programId;

    for (const transition of concept.stateMachine.transitions) {
      const funcName = `${concept.canonicalName}_${transition.via}`;
      const matches =
        buildable &&
        ref!.instructionName!.replace(/[_\s]/g, "").toLowerCase() ===
          transition.via.replace(/[_\s]/g, "").toLowerCase();

      code += `/** ${transition.via}: ${transition.from} → ${transition.to} for ${concept.canonicalName} */\n`;

      if (matches && ref && programId) {
        const discBytes = (ref.discriminator!.match(/.{2}/g) ?? []).map((h) => parseInt(h, 16));
        const paramFields = ref
          .args!.map((a) => {
            const opt = a.type.startsWith("option<") ? "?" : "";
            return `${a.name}${opt}: ${mapIdlArgTypeToTs(a.type)}`;
          })
          .join("; ");
        const accountFields = ref
          .accounts!.map((a) => `${a.name}${a.address ? "?" : ""}: string`)
          .join("; ");
        const ixDef = JSON.stringify({
          name: ref.instructionName,
          discriminator: discBytes,
          accounts: ref.accounts!.map((a) => ({
            name: a.name,
            writable: a.writable === true,
            signer: a.signer === true,
            ...(a.address ? { address: a.address } : {}),
          })),
          args: ref.args,
        });

        code += `export async function ${funcName}(\n`;
        code += `  params: { ${paramFields} },\n`;
        code += `  accounts: { ${accountFields} },\n`;
        code += `): Promise<ActionInstruction> {\n`;
        code += `  return compileInstruction(\n`;
        code += `    ${JSON.stringify(programId)},\n`;
        code += `    ${ixDef},\n`;
        code += `    params as unknown as Record<string, unknown>,\n`;
        code += `    accounts as unknown as Record<string, string>,\n`;
        code += `  );\n`;
        code += `}\n\n`;
      } else {
        code += `export async function ${funcName}(): Promise<ActionInstruction> {\n`;
        code += `  throw new Error(\n`;
        code += `    "${funcName}: no IDL instruction data for this transition in the ontology — " +\n`;
        code += `    "regenerate concepts from the program IDL (\`solana-ontology idl <program.json>\`) to enable it",\n`;
        code += `  );\n`;
        code += `}\n\n`;
      }
    }
  }

  return code;
}

/**
 * Generate Client.ts — main client class.
 */
export function generateClient(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n\n";
  code += "import type { OntologyClient } from '@solana-ontology/sdk';\n";
  code += "import type * as ObjectTypes from './ObjectTypes.js';\n\n";

  code += "export class SolanaOntologyClient {\n";
  code += "  constructor(private client: OntologyClient) {}\n\n";

  for (const concept of concepts) {
    code += `  /** Fetch a ${concept.canonicalName} by pubkey */\n`;
    code += `  async ${concept.canonicalName}(pubkey: string): Promise<ObjectTypes.${concept.canonicalName} | null> {\n`;
    code += `    const account = await this.client.fetchAccount(pubkey);\n`;
    code += `    return account as ObjectTypes.${concept.canonicalName} | null;\n`;
    code += `  }\n\n`;
  }

  code += "}\n";
  return code;
}

// ── base58 (for embedding a discriminator memcmp filter as a literal) ────────
const B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function encodeBase58(bytes: number[]): string {
  const digits: number[] = [];
  for (const byte of bytes) {
    let carry = byte;
    for (let i = 0; i < digits.length; i++) {
      carry += digits[i] << 8;
      digits[i] = carry % 58;
      carry = (carry / 58) | 0;
    }
    while (carry > 0) {
      digits.push(carry % 58);
      carry = (carry / 58) | 0;
    }
  }
  let prefix = "";
  for (const byte of bytes) {
    if (byte !== 0) break;
    prefix += "1";
  }
  return (
    prefix +
    digits
      .reverse()
      .map((d) => B58[d])
      .join("")
  );
}

/**
 * Generate Queries.ts — async iterator + filter functions.
 *
 * Concepts with an accountLayout discriminator get a real getProgramAccounts
 * query (discriminator memcmp filter) that decodes each account via a
 * caller-supplied decoder — the `decode<Name>` function emitted by
 * @solana-ontology/generator-ts. Concepts without a discriminator have no
 * filter/decoder and throw an explicit unsupported error.
 */
export function generateQueries(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n";
  code += "// DO NOT EDIT — regenerate with: solana-ontology generate client\n\n";
  code += "import type * as ObjectTypes from './ObjectTypes.js';\n\n";
  code += "/** Minimal duck-typed web3.js Connection surface used by the queries. */\n";
  code += "export interface QueryConnection {\n";
  code +=
    "  getProgramAccounts(programId: unknown, config?: unknown): Promise<Array<{ pubkey: { toBase58(): string }; account: { data: Uint8Array } }>>;\n";
  code += "}\n\n";

  for (const concept of concepts) {
    const name = concept.canonicalName;
    const disc = concept.accountLayout?.discriminator;

    if (!disc) {
      code += `/** Iterating ${name} is unavailable: its concept declares no accountLayout discriminator. */\n`;
      code += `export async function* iterate${name}(): AsyncGenerator<ObjectTypes.${name}> {\n`;
      code += `  throw new Error(\n`;
      code += `    "iterate${name}: concept has no accountLayout discriminator in the ontology — " +\n`;
      code += `    "add one (or run \`solana-ontology idl <program.json>\`) to enable program-account queries",\n`;
      code += `  );\n`;
      code += `}\n\n`;
      code += `/** Unavailable for the same reason as iterate${name}. */\n`;
      code += `export async function filter${name}(): Promise<ObjectTypes.${name}[]> {\n`;
      code += `  throw new Error(\n`;
      code += `    "filter${name}: concept has no accountLayout discriminator in the ontology — " +\n`;
      code += `    "add one (or run \`solana-ontology idl <program.json>\`) to enable program-account queries",\n`;
      code += `  );\n`;
      code += `}\n\n`;
      continue;
    }
    {
      const discBytes = (disc.match(/.{2}/g) ?? []).map((h) => parseInt(h, 16));
      const b58 = encodeBase58(discBytes);
      code += `/**\n`;
      code += ` * Stream every ${name} account owned by \`programId\`, decoded via \`decode\`\n`;
      code += ` * (the decode${name} function from your generated @solana-ontology/generator-ts output).\n`;
      code += ` */\n`;
      code += `export async function* iterate${name}(\n`;
      code += `  connection: QueryConnection,\n`;
      code += `  programId: string,\n`;
      code += `  decode: (data: Uint8Array) => Omit<ObjectTypes.${name}, "pubkey">,\n`;
      code += `): AsyncGenerator<ObjectTypes.${name}> {\n`;
      code += `  const accounts = await connection.getProgramAccounts(programId, {\n`;
      code += `    filters: [{ memcmp: { offset: 0, bytes: ${JSON.stringify(b58)} } }],\n`;
      code += `  });\n`;
      code += `  for (const { pubkey, account } of accounts) {\n`;
      code += `    yield { pubkey: pubkey.toBase58(), ...decode(account.data) } as ObjectTypes.${name};\n`;
      code += `  }\n`;
      code += `}\n\n`;
    }

    code += `export async function filter${name}(\n`;
    code += `  connection: QueryConnection,\n`;
    code += `  programId: string,\n`;
    code += `  decode: (data: Uint8Array) => Omit<ObjectTypes.${name}, "pubkey">,\n`;
    code += `  predicate: (account: ObjectTypes.${name}) => boolean,\n`;
    code += `): Promise<ObjectTypes.${name}[]> {\n`;
    code += `  const results: ObjectTypes.${name}[] = [];\n`;
    code += `  for await (const account of iterate${name}(connection, programId, decode)) {\n`;
    code += `    if (predicate(account)) results.push(account);\n`;
    code += `  }\n`;
    code += `  return results;\n`;
    code += `}\n\n`;
  }

  return code;
}

/**
 * Generate all client files.
 */
export function generateClientFiles(
  concepts: Concept[],
  config: ClientGenConfig,
): GeneratedClientFile[] {
  const files: GeneratedClientFile[] = [
    { path: "ObjectTypes.ts", content: generateObjectTypes(concepts) },
    { path: "ActionTypes.ts", content: generateActionTypes(concepts) },
    { path: "Client.ts", content: generateClient(concepts) },
  ];

  if (config.generateQueries) {
    files.push({ path: "Queries.ts", content: generateQueries(concepts) });
  }

  if (config.generateReact) {
    files.push({ path: "Hooks.ts", content: generateReactHooks(concepts) });
  }

  // Index barrel
  files.push({
    path: "index.ts",
    content: [
      "export * from './ObjectTypes.js';",
      "export * from './ActionTypes.js';",
      "export * from './Client.js';",
      config.generateQueries ? "export * from './Queries.js';" : "",
      config.generateReact ? "export * from './Hooks.js';" : "",
    ]
      .filter(Boolean)
      .join("\n"),
  });

  return files;
}

/**
 * Generate React hooks for each concept.
 */
function generateReactHooks(concepts: Concept[]): string {
  let code = "// Auto-generated by @solana-ontology/generator-client\n\n";
  code += "import { useEffect, useState } from 'react';\n";
  code += "import type { OntologyClient } from '@solana-ontology/sdk';\n";
  code += "import type * as ObjectTypes from './ObjectTypes.js';\n\n";

  for (const concept of concepts) {
    const name = concept.canonicalName;
    code += `export function use${name}(client: OntologyClient | null, pubkey: string | null) {\n`;
    code += `  const [data, setData] = useState<ObjectTypes.${name} | null>(null);\n`;
    code += `  const [loading, setLoading] = useState(false);\n`;
    code += `  const [error, setError] = useState<Error | null>(null);\n\n`;
    code += `  useEffect(() => {\n`;
    code += `    if (!client || !pubkey) return;\n`;
    code += `    setLoading(true);\n`;
    code += `    client.fetchAccount(pubkey)\n`;
    code += `      .then((acc) => setData(acc as ObjectTypes.${name} | null))\n`;
    code += `      .catch(setError)\n`;
    code += `      .finally(() => setLoading(false));\n`;
    code += `  }, [client, pubkey]);\n\n`;
    code += `  return { data, loading, error };\n`;
    code += `}\n\n`;
  }

  return code;
}
