import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import type { Concept } from "@solana-ontology/core";
import { generateAccountInterface, generateDecoder, generateEncoder } from "./account-gen.js";
import { generatePdaHelper } from "./pda-gen.js";
import { generateActions, generateStateEnum } from "./action-gen.js";
import { generateQuery, generateBatchQuery } from "./query-gen.js";

export interface GenerateOptions {
  outputDir: string;
  /** Whether to generate a barrel index file */
  generateIndex?: boolean;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Generate all TypeScript files for a single concept.
 */
export function generateConceptFiles(concept: Concept): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const name = concept.canonicalName;
  const fileName = name.charAt(0).toLowerCase() + name.slice(1);

  const parts: string[] = [];

  parts.push(generateAccountInterface(concept));
  parts.push("");
  parts.push(generateDecoder(concept));
  parts.push("");
  parts.push(generateEncoder(concept));

  const pdaHelper = generatePdaHelper(concept);
  if (pdaHelper) {
    parts.push("");
    parts.push(pdaHelper);
  }

  const stateEnum = generateStateEnum(concept);
  if (stateEnum) {
    parts.push("");
    parts.push(stateEnum);
  }

  const actions = generateActions(concept);
  for (const action of actions) {
    parts.push("");
    parts.push(action);
  }

  parts.push("");
  parts.push(generateQuery(concept));
  parts.push("");
  parts.push(generateBatchQuery(concept));

  files.push({
    path: `${fileName}.ts`,
    content: parts.join("\n"),
  });

  return files;
}

/**
 * Generate a barrel index file re-exporting all concept modules.
 */
export function generateIndexFile(concepts: Concept[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by @solana-ontology/generator-ts",
    "// Do not edit manually — run `solana-ontology generate` instead.",
    "",
  ];

  for (const concept of concepts) {
    const name = concept.canonicalName;
    const fileName = name.charAt(0).toLowerCase() + name.slice(1);
    lines.push(`export * from "./${fileName}.js";`);
  }

  return lines.join("\n");
}

/**
 * Generate all TypeScript files for an array of concepts and write them to disk.
 */
export function generateAll(
  concepts: Concept[],
  options: GenerateOptions,
): GeneratedFile[] {
  const allFiles: GeneratedFile[] = [];
  mkdirSync(options.outputDir, { recursive: true });

  for (const concept of concepts) {
    const files = generateConceptFiles(concept);
    for (const file of files) {
      const fullPath = join(options.outputDir, file.path);
      mkdirSync(dirname(fullPath), { recursive: true });
      writeFileSync(fullPath, file.content, "utf-8");
      allFiles.push({ path: fullPath, content: file.content });
    }
  }

  if (options.generateIndex !== false) {
    const indexContent = generateIndexFile(concepts);
    const indexPath = join(options.outputDir, "index.ts");
    writeFileSync(indexPath, indexContent, "utf-8");
    allFiles.push({ path: indexPath, content: indexContent });
  }

  return allFiles;
}
