# yaml-language-server: $schema=none
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solana-ontology.fullname" . }}-secrets
  labels:
    app: solana-ontology
type: Opaque
stringData:
  rpcApiKey: {{ .Values.secrets.rpcApiKey | quote }}
  kmsKeyId: {{ .Values.secrets.kmsKeyId | quote }}
  mpcWebhookToken: {{ .Values.secrets.mpcWebhookToken | quote }}
  omsAuthToken: {{ .Values.secrets.omsAuthToken | quote }}
